<?php

namespace App\Services\Disputes;

use Illuminate\Support\Str;

class DisputeEventLabelService
{
    public function label(string $action): string
    {
        return match ($action) {
            'dispute.opened' => __('Dispute file opened'),
            'dispute.message_added' => __('Party posted an update'),
            'dispute.settlement_offered' => __('Settlement offer submitted'),
            'dispute.settlement_accepted' => __('Settlement offer accepted'),
            'dispute.settlement_declined' => __('Settlement offer declined'),
            'dispute.resolution_proposed' => __('Party proposed a resolution outcome'),
            'negotiation.started' => __('Peer negotiation started'),
            'negotiation.proposed' => __('Negotiation proposal submitted'),
            'negotiation.accepted' => __('Negotiation proposal accepted'),
            'negotiation.escalated_mediation' => __('Escalated to staff mediation'),
            'negotiation.binding_mediation_ack' => __('Party acknowledged binding mediation'),
            'negotiation.mutual_approved' => __('Mutual agreement approved by staff'),
            'negotiation.enforcement_executed' => __('Mediation decision enforced'),
            'negotiation.finalized' => __('Dispute finalized'),
            'appeal.filed' => __('Party filed an appeal'),
            'appeal.counter_response' => __('Response to appeal submitted'),
            'super_admin.decision_pending_enforcement' => __('Decision issued — enforcement window open'),
            'super_admin.appeal_resolved' => __('Appeal resolved — final binding'),
            'dispute.mutual_resolve_ack' => __('Party agreed to mutual resolve'),
            'dispute.party_self_resolved' => __('Parties closed the dispute themselves'),
            'management.party_resolution_acknowledged' => __('Super Admin acknowledged party resolution'),
            'dispute.escalated_silence' => __('Escalated — response window expired'),
            'dispute.auto_timed_split' => __('Auto-resolved with default split'),
            'management.auto_assigned' => __('Assigned to staff investigator'),
            'management.ready_for_decision' => __('Marked ready for Super Admin decision'),
            'management.reassigned' => __('Reassigned to another staff member'),
            'management.finalized' => __('Dispute finalized'),
            'staff_claimed' => __('Staff claimed the case'),
            'staff_internal_note' => __('Staff internal note'),
            'staff_notice' => __('Staff notice posted to parties'),
            'staff_contact' => __('Staff mediated message sent'),
            'staff_evidence_request' => __('Staff requested more evidence'),
            'staff_assessment_saved' => __('Staff saved assessment draft'),
            'staff_assessment_submitted' => __('Staff submitted assessment'),
            'super_admin.decision_executed' => __('Super Admin decision executed'),
            'super_admin.request_more_review' => __('Super Admin requested more review'),
            'staff_acknowledged' => __('Staff acknowledged dispute'),
            'staff_checklist_updated' => __('Investigation checklist updated'),
            'staff_evidence_reviewed' => __('Evidence marked as reviewed'),
            'staff_awaiting_info' => __('Marked awaiting party information'),
            'staff_reassign_requested' => __('Staff requested reassignment'),
            'super_admin.private_note' => __('Super Admin private note'),
            'super_admin.request_clarification' => __('Super Admin requested staff clarification'),
            'staff.clarification_response' => __('Staff responded to Super Admin clarification'),
            'staff.more_review_response' => __('Staff responded to Super Admin review request'),
            'super_admin.evidence_request' => __('Super Admin requested evidence'),
            'super_admin.direct_message' => __('Super Admin messaged party directly'),
            'super_admin.hold' => __('Dispute placed on hold'),
            'super_admin.hold_released' => __('Dispute hold released'),
            'super_admin.rated_assessment' => __('Super Admin rated staff assessment'),
            'super_admin.appeal_review_opened' => __('Appeal review opened'),
            'mediation.scheduled' => __('Mediation session scheduled'),
            'mediation.completed' => __('Mediation session completed'),
            'outcome.force_revision' => __('Force revision ordered'),
            'outcome.deadline_extended' => __('Deadline extended'),
            'outcome.contract_terminated' => __('Contract terminated'),
            'admin.chargeback_risk_flagged' => __('Chargeback risk flagged'),
            'admin.pattern_investigation_opened' => __('Pattern investigation opened'),
            'admin.precedent_created' => __('Precedent recorded'),
            'admin.report_generated' => __('PDF report generated'),
            'admin.sealed_archived' => __('Dispute sealed and archived'),
            'sanction.warning_issued' => __('Formal warning issued'),
            'sanction.suspension_issued' => __('Account suspension issued'),
            'sanction.ban_issued' => __('Permanent ban issued'),
            'sanction.tier_demoted' => __('Verification tier demoted'),
            'sanction.category_ban' => __('Category ban applied'),
            default => Str::headline(str_replace(['.', '_'], ' ', $action)),
        };
    }
}
