<?php

return [
    'health_score' => [
        'default' => 100,
        'risk_queue_threshold' => (int) env('CONVERSATION_HEALTH_RISK_THRESHOLD', 45),
    ],

    'penalties' => [
        'off_platform_payment' => 22,
        'external_contact' => 18,
        'abusive_language' => 15,
        'blacklisted_keyword' => 8,
        'cross_party_multiplier' => 1.35,
        'repeat_same_party_multiplier' => 0.85,
    ],

    'systematic' => [
        'window_days' => 30,
        'min_distinct_counterparties' => 3,
        'min_instances' => 3,
        'categories' => ['off_platform_payment', 'external_contact'],
    ],

    'fuzzy' => [
        'max_levenshtein' => 2,
        'min_token_length' => 4,
    ],

    'off_platform_phrases' => [
        'pay me directly',
        'pay directly',
        'pay outside',
        'pay off platform',
        'outside the platform',
        'off platform',
        'send it to my account',
        'send to my account',
        'my account number',
        'dont use the platform',
        "don't use the platform",
        'do not use the platform',
        'let me pay you outside',
    ],

        'contact_phrases' => [
            'whatsapp me',
            'ping me on whatsapp',
            'on whatsapp',
            'reach me on whatsapp',
            'on telegram',
            'telegram me',
            'teleg',
            'tgm',
            'dm me',
            'dm me on',
            'slide into my dms',
            'slide into dms',
            'slide in my dms',
            'slide into',
            'my dms',
            'my dm',
            'add me on snap',
            'on snapchat',
            'on snap',
            'on instagram',
            'on insta',
            'on twitter',
            'on tweeter',
            'on x.com',
            'on x',
            'on fb',
            'on facebook',
            'my handle',
            'social handle',
            'email me',
            'send email',
            'send me email',
            'send me an email',
            'mail me',
            'call me',
            'give me a call',
            'reach me on',
            'contact me on',
            'find me on',
            'message me on',
        ],

        'contact_short_tokens' => [
            'dm',
            'dms',
            'pm',
            'fb',
            'ig',
            'insta',
            'snap',
            'tgm',
            'teleg',
            'wa',
            'whatsapp',
            'telegram',
            'snapchat',
            'twitter',
            'tweeter',
            'gmail',
            'yahoo',
            'hotmail',
            'outlook',
        ],

        'spoken_digit_words' => [
            'zero', 'oh', 'o', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine',
        ],
];
