<?php

return [
    'definitions' => [
        'dispute_resolution' => [
            'label' => 'Dispute resolution',
            'setting_key' => 'sla.dispute_resolution.working_days',
            'unit' => 'working_days',
            'default' => 10,
            'admin_action_url' => '/admin/disputes',
            'user_message' => 'We aim to resolve this dispute within :duration.',
        ],
        'kyc_verification' => [
            'label' => 'KYC verification review',
            'setting_key' => 'sla.kyc_verification.hours',
            'unit' => 'hours',
            'default' => 24,
            'admin_action_url' => '/admin/verification-engine',
            'user_message' => 'We aim to complete your verification review within :duration.',
        ],
        'escrow_release_appeal' => [
            'label' => 'Escrow release review',
            'setting_key' => 'sla.escrow_release_appeal.hours',
            'unit' => 'hours',
            'default' => 48,
            'admin_action_url' => '/admin/financial',
            'user_message' => 'We aim to review this escrow release request within :duration.',
        ],
        'support_ticket_response' => [
            'label' => 'Support ticket response',
            'setting_key' => 'sla.support_ticket_response.working_days',
            'unit' => 'working_days',
            'default' => 10,
            'admin_action_url' => '/admin/support-tickets',
            'user_message' => 'We aim to resolve your support request within :duration.',
        ],
        'quest_moderation_review' => [
            'label' => 'Quest moderation review',
            'setting_key' => 'sla.quest_moderation_review.hours',
            'unit' => 'hours',
            'default' => 48,
            'admin_action_url' => '/admin/moderation?module=quests',
            'user_message' => 'We aim to complete this quest review within :duration.',
        ],
        'proposal_moderation_review' => [
            'label' => 'Proposal moderation review',
            'setting_key' => 'sla.proposal_moderation_review.hours',
            'unit' => 'hours',
            'default' => 48,
            'admin_action_url' => '/admin/moderation?module=proposals',
            'user_message' => 'We aim to complete this proposal review within :duration.',
        ],
        'content_moderation' => [
            'label' => 'Content moderation',
            'setting_key' => 'sla.content_moderation.hours',
            'unit' => 'hours',
            'default' => 24,
            'admin_action_url' => '/admin/content-moderation',
            'user_message' => 'We aim to review this content within :duration.',
        ],
        'portfolio_review' => [
            'label' => 'Portfolio review',
            'setting_key' => 'sla.portfolio_review.working_days',
            'unit' => 'working_days',
            'default' => 5,
            'admin_action_url' => '/admin/portfolio-review',
            'user_message' => 'We aim to review your portfolio within :duration.',
        ],
        'review_moderation' => [
            'label' => 'Review & rating moderation',
            'setting_key' => 'sla.review_moderation.hours',
            'unit' => 'hours',
            'default' => 72,
            'admin_action_url' => '/admin/content-moderation',
            'user_message' => 'We aim to complete this review moderation within :duration.',
        ],
        'financial_review' => [
            'label' => 'Financial review',
            'setting_key' => 'sla.financial_review.hours',
            'unit' => 'hours',
            'default' => 48,
            'admin_action_url' => '/admin/financial-review',
            'user_message' => 'We aim to complete this financial review within :duration.',
        ],
        'onboarding_quality_review' => [
            'label' => 'Onboarding quality review',
            'setting_key' => 'sla.onboarding_quality_review.working_days',
            'unit' => 'working_days',
            'default' => 3,
            'admin_action_url' => '/admin/onboarding-quality',
            'user_message' => 'We aim to complete your profile quality review within :duration.',
        ],
        'sanction_appeal' => [
            'label' => 'Sanction appeal review',
            'setting_key' => 'sla.sanction_appeal.working_days',
            'unit' => 'working_days',
            'default' => 5,
            'admin_action_url' => '/admin/trust-risk',
            'user_message' => 'We aim to review your appeal within :duration.',
        ],
    ],
];
